title: Julio Merino
author: Julio Merino
email: julio@meroh.net

description: >
  This is Julio Merino's homepage.  This site acts as the gateway to my
  presence in the web, and summarizes all my work.  In fact, you can
  think of this page as my extended r&eacute;sum&eacute; or portfolio.

environment: production

baseurl: ""
permalink: /:year/:month/:title.html
url: http://julio.meroh.net

exclude:
  - Makefile
  - Makefile.in
  - README.md
  - blog/README.md
  - configure
  - external

gems: [jekyll-archives, jekyll-paginate]

jekyll-archives:
  enabled:
    - month
    - year
  layouts:
    month: month
    year: year
  permalinks:
    month: '/:year/:month/'
    year: '/:year/'

paginate: 7
paginate_path: /page:num

analytics_account: UA-63557333-1

highlighter: rouge
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
