title: Julio Merino
author: Julio Merino
email: julio@meroh.net

last_updated: March 2nd, 2016

description: >
  This is Julio Merino's homepage.  This site acts as the gateway to my
  presence in the web, and summarizes all my work.  In fact, you can
  think of this page as my extended r&eacute;sum&eacute; or portfolio.

baseurl: ""
permalink: /blog/:year/:month/:day/:title.html
url: http://julio.meroh.net

analytics_account: UA-63557333-1

highlighter: rouge
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
